---
  - name: Install Nginx
    package:
      pkg: nginx
      state: present
      update_cache: yes
    tags: ["nginx"]

  - name: Copy files
    copy:
      src: files/{{ item }}
      dest: /etc/nginx/snippets/
    with_items:
      - general.conf
      - ssl.conf
      - security.conf
    tags: ["nginx"]

  - name: Updating nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
    tags: ["nginx"]
    notify: Restart nginx

  - name: Updating default.conf
    template:
      src: default.conf.j2
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: 0644
    tags: ["nginx"]
    notify: Reload nginx

  - name: iptables open {{ nginx.listen_http_port }} port
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ nginx.listen_http_port }}"
      jump: ACCEPT
    notify: save iptables
    tags: ["nginx", "iptables", "nginx_iptables"]